### ISSUE TITLE
Feature request, Can we use translate API for auto translate, then modify the translated content? 

### ISSUE THREAD

**Issue by selfhostrepo** [hugomods/i18n-js#8]
For example,  we have deepL translate api, and we have written a blog in English, would like to use API to auto translate the blog into other language, then human author do the final check before publishing it. Thank you.

**Comment by razonyang** [comment]
I don't think it's possible to do that in theme's and module's side~

**Comment by razonyang** [comment]
You can use some tools, like GitHub action, to auto translate the content into other languages to achieve that, workflow:

1. Translate content on push.
2. Create a PR.
3. Review and reject/merge.

I couldn't provide an example, but it should work.
